### ISSUE TITLE
support for Apple music

### ISSUE THREAD

**Issue by PaulLaux** [cross-platform/icloud-for-linux#12] opened 2020-04-24 06:30 UTC
Now that Apple music for web is out of beta, would it be possible to add it as part of this wonderful package?

https://music.apple.com/us/browse

**Comment by MarcusTomlinson** [comment] 2020-04-24 08:40
Hey @PaulLaux, I have looked into this and learnt that it would be quite tricky to pull off. I'll certainly revisit the idea though.

It's not that snapping Apple Music is difficult. The issue is the legality of it. In order to support DRM-encrypted media streaming, the snap would need access to the Widevine CDM library. Embedding this into the snap is not legal, so users would need to download it separately and save it somewhere specific for the snap to pick up. This is easier said than done though. For this to work, the user would be expected to download the exact right version of Widevine for the exact right version of browser engine the snap is using. Not impossible, just tricky.

I wouldn't add Apple Music to this snap however, I would create an entirely new one, so I'm going to close this issue as it doesn't fit into the scope of this project.

**Closed by MarcusTomlinson** 2020-04-24 08:40 UTC

**Comment by MarcusTomlinson** [comment] 2020-04-24 19:48
@PaulLaux, so it's not pretty but it works: https://snapcraft.io/apple-music-for-linux
