### ISSUE TITLE
Does not sync icloud drive data down to device.

### ISSUE THREAD

**Issue by jecsanb** [cross-platform/icloud-for-linux#14] opened 2020-06-12 03:10 UTC
Is the app just suppose to display things like the browser?
I found this to try to sync my iCloud stuff on my linux computer the same way it works on the
windows app. Is doing that possible with these apps? If not is there a future update that would allow the sync?

**Comment by MarcusTomlinson** [comment] 2020-06-12 04:22
Duplicate of: https://github.com/cross-platform/icloud-for-linux/issues/7

**Closed** 2020-06-12 04:23 UTC
Labels: duplicate
